version: '3'

services:

  mysql-development:
    platform: linux/x86_64
    image: mysql:8.0.26
    environment:
      MYSQL_ROOT_PASSWORD: ${DBPASS}
      MYSQL_DATABASE: highlightit
    ports:
      - "3308:3306"
    volumes:
      - "./init/setup.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./init/default.sql:/docker-entrypoint-initdb.d/2.sql"